packages:
  # all packages in subdirs of packages/ and components/
  - "packages/*"
  # - 'components/**'
  # # exclude packages that are inside test directories
  # - '!**/test/**'
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
minimumReleaseAgeExclude:
  - dotenv@18.0.4
  - mithril-ui-form@2.3.3
